# Generated by Django 2.1.15 on 2020-07-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_id',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
